using LiteNetLib;
using LiteNetLib.Utils;
using Microsoft.Xna.Framework;
using Nez;
using Nez.Systems;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using WoW.Client.Components.Player;
using WoW.Client.Network;
using WoW.Client.Scenes;
using WoW.Framework.Logging;
using WoW.Framework.Network;
using WoW.Framework.Network.Container;

namespace WoW.Client.Utils
{
    public enum GameNetworkState
    {
        Offline,
        Offline_Realm,
        Offline_Characters,
        Offline_World,
        Auth_LoggingIn,
        Auth_Banned,
        Auth_Invalid,
        Auth_IsOnline,
        Auth_Realmlist,
        Realm,
        Realm_Characters,
        Realm_CreateCharacter,
        Realm_CharacterNameInvalid,
        LoadingWorld,
        World
    }

    /// <summary>
    /// Potentially globally used functions; typically emitted from some location.
    /// </summary>
    public class GameManager : GlobalManager
    {
        #region event handlers

        /// <summary>
        /// Triggers  whenever local player movement is != Vector2.Zero.
        /// </summary>
        public EventHandler<Vector2> LocalPlayerMoved;

        /// <summary>
        /// Triggers when a new actor has been sent to this client.
        /// </summary>
        public EventHandler<Entity> NewActor;

        /// <summary>
        /// Triggers when this client gets disconnected from the server, either by kick or otherwise.
        /// </summary>
        public EventHandler Disconnected;

        public EventHandler<(string username, string password)> LogonClicked;

        #endregion

        private List<(long Tick, Vector2 Input, Vector2 ResultingClientPosition)> _movementTickChanges;

        private Queue<Entity> _newActorQueue = new Queue<Entity>();
        private Queue<QueueablePacket> _packetQueue = new Queue<QueueablePacket>();

        /// <summary>
        /// The local player entity object. Use this to get your character's component data.
        /// </summary>
        public Entity Player;

        /// <summary>
        /// The network peer. 
        /// 
        /// This is set upon connecting to a server successfully.
        /// </summary>
        public NetPeer Peer = null;
        public NetworkManager Network;
        public GameNetworkState PeerState = GameNetworkState.Offline;

        /// <summary>
        /// A unique id generated by the server.
        /// </summary>
        public string NetworkId = "-";

        /// <summary>
        /// The list of realms provided by the Authserver.
        /// </summary>
        public List<RealmserverContainer> Realmlist = new List<RealmserverContainer>();

        public List<ChatMessageContainer> ChatHistory = new List<ChatMessageContainer>();

        public GameManager(bool subscribeDefaults = true)
        {
            LocalPlayerMoved += OnLocalPlayerMoved;
            NewActor += OnNewActor;
            Disconnected += OnDisconnected;
            LogonClicked += OnLoginClicked;

            _movementTickChanges = new List<(long tick, Vector2 input, Vector2 resultingPosition)>();
        }

        private void OnLoginClicked(object sender, (string username, string password) logonArgs)
        {
            PeerState = GameNetworkState.Auth_LoggingIn;
            Network.ConnectTo(ConfigurationManager.AppSettings["realmlist"].Split(":"));

            NetPacketManager.BuildLogon(new[]
            {
                $"{logonArgs.username}",
                $"{logonArgs.password}"
            });
        }

        #region Default subscribers

        /// <summary>
        /// Triggered when the local player moves.
        /// </summary>
        /// <param name="sender"></param>
        /// <param name="input"></param>
        public void OnLocalPlayerMoved(object sender, Vector2 input)
        {
            if (PeerState == GameNetworkState.World)
            {
                Entity myPlayer = Core.Scene.FindComponentOfType<MyPlayerControllerComponent>().Entity;
                long movementTimeTick = DateTime.Now.Ticks; // used to track individual input during reconciliation.

                _movementTickChanges.Add(new(movementTimeTick, input, myPlayer.Position)); // stores relevant movement information at the time of processing so when the server sends us our real calcuation, we can cross-check and reconcile.

                NetPacketManager.BuildMovementUpdate(input, movementTimeTick);
            }
        }

        /// <summary>
        /// Queues an Actor for processing that was created by the server.
        /// </summary>
        /// <param name="sender"></param>
        /// <param name="entity"></param>
        public void OnNewActor(object sender, Entity entity)
        {
            _newActorQueue.Enqueue(entity);
        }

        /// <summary>
        /// Handles a disconnection.
        /// </summary>
        /// <param name="sender"></param>
        /// <param name="e"></param>
        [Obsolete("Unused still as of 8/9.")]
        public void OnDisconnected(object sender, EventArgs e) 
        {
            var gui = Core.Scene.FindEntity("gui");

            Player.Destroy();
            Realmlist.Clear();
            Network.Disconnect();
            PeerState = GameNetworkState.Offline;

            Core.StartSceneTransition(new FadeTransition(() => new LogonScene()));
        }
        #endregion

        /// <summary>
        /// Pops an Actor from the queue that was created by the server and begins processing it.
        /// </summary>
        /// <param name="entity"></param>
        /// <returns></returns>
        public bool PopUntrackedActor(out Entity entity)
        {
            if (_newActorQueue.TryDequeue(out var result))
            {
                entity = result;
                return true;
            }

            entity = null;
            return false;
        }

        public void QueuePacket(QueueablePacket writer) => _packetQueue.Enqueue(writer);

        public bool PopPacket(out QueueablePacket writer)
        {
            if (_packetQueue.TryDequeue(out var result))
            {
                writer = result;
                return true;
            }

            writer = null;
            return false;
        }

        /// <summary>
        /// Attempts to locate a movement change by it's <see cref="DateTime.Now"/> value in Ticks (long).
        /// </summary>
        /// <param name="timeTick"></param>
        /// <returns></returns>
        public Tuple<long, Vector2, Vector2> FindMovementChangeByTick(long timeTick) => _movementTickChanges.Find((tuple) => tuple.Tick == timeTick).ToTuple();
    }
}
