// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WoW.Server.Shared.Database;
using WoW.Server.Shared.Database.Model;

#nullable disable

namespace WoW.Realmserver.Migrations
{
    [DbContext(typeof(RealmContext))]
    [Migration("20241215075557_RemoveKeyFromCharacter")]
    partial class RemoveKeyFromCharacter
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("WoW.Server.Shared.Database.Model.PlayerCharacter", b =>
                {
                    b.Property<string>("Name")
                        .HasColumnType("varchar(16)")
                        .HasColumnName("character_name");

                    b.Property<int>("AccountId")
                        .HasColumnType("int")
                        .HasColumnName("account_id");

                    b.Property<int>("CharacterId")
                        .HasColumnType("int")
                        .HasColumnName("character_id");

                    b.Property<float>("XPosition")
                        .HasColumnType("float")
                        .HasColumnName("zone_x_position");

                    b.Property<float>("YPosition")
                        .HasColumnType("float")
                        .HasColumnName("zone_y_position");

                    b.HasKey("Name");

                    b.ToTable("characters");
                });
#pragma warning restore 612, 618
        }
    }
}
