// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WoW.Server.Shared.Database;
using WoW.Server.Shared.Database.Model;

#nullable disable

namespace WoW.Realmserver.Migrations
{
    [DbContext(typeof(RealmContext))]
    [Migration("20250101062235_AddNpcTables")]
    partial class AddNpcTables
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("WoW.Server.Shared.Database.Model.NPC_Behavior", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<int>("BehaviorType")
                        .HasColumnType("int")
                        .HasColumnName("behavior_type");

                    b.Property<int>("NpcId")
                        .HasColumnType("int")
                        .HasColumnName("npc_id");

                    b.Property<string>("Script")
                        .HasColumnType("longtext")
                        .HasColumnName("script");

                    b.HasKey("Id");

                    b.ToTable("npc_behavior");
                });

            modelBuilder.Entity("WoW.Server.Shared.Database.Model.NonPlayerCharacter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("FlagType")
                        .HasColumnType("int")
                        .HasColumnName("npc_flag");

                    b.Property<int>("Level")
                        .HasColumnType("int")
                        .HasColumnName("level");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("npc");
                });

            modelBuilder.Entity("WoW.Server.Shared.Database.Model.PlayerCharacter", b =>
                {
                    b.Property<string>("Name")
                        .HasColumnType("varchar(16)")
                        .HasColumnName("character_name");

                    b.Property<int>("AccountId")
                        .HasColumnType("int")
                        .HasColumnName("account_id");

                    b.Property<int>("CharacterId")
                        .HasColumnType("int")
                        .HasColumnName("character_id");

                    b.Property<float>("XPosition")
                        .HasColumnType("float")
                        .HasColumnName("zone_x_position");

                    b.Property<float>("YPosition")
                        .HasColumnType("float")
                        .HasColumnName("zone_y_position");

                    b.HasKey("Name");

                    b.ToTable("characters");
                });
#pragma warning restore 612, 618
        }
    }
}
