// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WoW.Server.Shared.Database;
using WoW.Server.Shared.Database.Model;

#nullable disable

namespace WoW.Realmserver.Migrations
{
    [DbContext(typeof(RealmContext))]
    [Migration("20250203223431_UpdateBehaviorsTable")]
    partial class UpdateBehaviorsTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("WoW.Server.Shared.Database.Model.CharacterRaceSpawn", b =>
                {
                    b.Property<int>("RaceId")
                        .HasColumnType("int")
                        .HasColumnName("race_id");

                    b.Property<string>("MapId")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("map_id");

                    b.Property<float>("X")
                        .HasColumnType("float")
                        .HasColumnName("x_position");

                    b.Property<float>("Y")
                        .HasColumnType("float")
                        .HasColumnName("y_position");

                    b.HasKey("RaceId");

                    b.ToTable("character_race_spawn");
                });

            modelBuilder.Entity("WoW.Server.Shared.Database.Model.Chat.ChatCommand", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("command_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("HandlerId")
                        .HasColumnType("longtext")
                        .HasColumnName("handler_id");

                    b.Property<string>("HelpText")
                        .HasColumnType("longtext")
                        .HasColumnName("help_text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("name");

                    b.Property<int>("Security")
                        .HasColumnType("int")
                        .HasColumnName("security_level");

                    b.HasKey("Id");

                    b.ToTable("chat_command");
                });

            modelBuilder.Entity("WoW.Server.Shared.Database.Model.Chat.ChatCommandChild", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("child_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("HandlerId")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("handler_id");

                    b.Property<string>("HelpText")
                        .HasColumnType("longtext")
                        .HasColumnName("help_text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("name");

                    b.Property<int>("ParentId")
                        .HasColumnType("int")
                        .HasColumnName("parent_id");

                    b.Property<int>("Security")
                        .HasColumnType("int")
                        .HasColumnName("security_level");

                    b.HasKey("Id");

                    b.ToTable("chat_command_children");
                });

            modelBuilder.Entity("WoW.Server.Shared.Database.Model.NonPlayerCharacter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("FlagType")
                        .HasColumnType("int")
                        .HasColumnName("npc_flag");

                    b.Property<int>("Level")
                        .HasColumnType("int")
                        .HasColumnName("level");

                    b.Property<string>("ModelId")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("model_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("npc");
                });

            modelBuilder.Entity("WoW.Server.Shared.Database.Model.NonPlayerCharacterBehaviors", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("NpcId")
                        .HasColumnType("int")
                        .HasColumnName("npc_id");

                    b.Property<string>("Script")
                        .HasColumnType("longtext")
                        .HasColumnName("behavior_code_id");

                    b.HasKey("Id");

                    b.ToTable("npc_behavior");
                });

            modelBuilder.Entity("WoW.Server.Shared.Database.Model.PlayerCharacter", b =>
                {
                    b.Property<string>("Name")
                        .HasColumnType("varchar(16)")
                        .HasColumnName("character_name");

                    b.Property<int>("AccountId")
                        .HasColumnType("int")
                        .HasColumnName("account_id");

                    b.Property<int>("CharacterId")
                        .HasColumnType("int")
                        .HasColumnName("character_id");

                    b.Property<int>("Direction")
                        .HasColumnType("int")
                        .HasColumnName("animation_direction");

                    b.Property<int>("HairId")
                        .HasColumnType("int")
                        .HasColumnName("character_hair_id");

                    b.Property<string>("MapId")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("map_id");

                    b.Property<int>("RaceId")
                        .HasColumnType("int")
                        .HasColumnName("character_race_id");

                    b.Property<float>("XPosition")
                        .HasColumnType("float")
                        .HasColumnName("zone_x_position");

                    b.Property<float>("YPosition")
                        .HasColumnType("float")
                        .HasColumnName("zone_y_position");

                    b.HasKey("Name");

                    b.ToTable("characters");
                });
#pragma warning restore 612, 618
        }
    }
}
