// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WoW.Database.Models;

#nullable disable

namespace WoW.Database.Migrations
{
    [DbContext(typeof(RealmContext))]
    [Migration("20260623022815_AddItemDefinition")]
    partial class AddItemDefinition
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.17")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("WoW.Database.Models.Realm.Character.CharacterClassBaseStatistic", b =>
                {
                    b.Property<int>("ClassId")
                        .HasColumnType("int")
                        .HasColumnName("class_id");

                    b.Property<int>("Agility")
                        .HasColumnType("int")
                        .HasColumnName("agility_amt");

                    b.Property<int>("Intellect")
                        .HasColumnType("int")
                        .HasColumnName("intellect_amt");

                    b.Property<int>("Spirit")
                        .HasColumnType("int")
                        .HasColumnName("spirit_amt");

                    b.Property<int>("Stamina")
                        .HasColumnType("int")
                        .HasColumnName("stamina_amt");

                    b.Property<int>("Strength")
                        .HasColumnType("int")
                        .HasColumnName("strength_amt");

                    b.HasKey("ClassId");

                    b.ToTable("character_class_stats");
                });

            modelBuilder.Entity("WoW.Database.Models.Realm.Character.CharacterRaceSpawn", b =>
                {
                    b.Property<int>("RaceId")
                        .HasColumnType("int")
                        .HasColumnName("race_id");

                    b.Property<string>("MapId")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("map_id");

                    b.Property<float>("X")
                        .HasColumnType("float")
                        .HasColumnName("x_position");

                    b.Property<float>("Y")
                        .HasColumnType("float")
                        .HasColumnName("y_position");

                    b.HasKey("RaceId");

                    b.ToTable("character_race_spawn");
                });

            modelBuilder.Entity("WoW.Database.Models.Realm.Character.FilteredCharacterName", b =>
                {
                    b.Property<int>("NameOrPhraseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("NameOrPhraseId"));

                    b.Property<string>("NameOrPhrase")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("phrase");

                    b.HasKey("NameOrPhraseId");

                    b.ToTable("character_name_filter");
                });

            modelBuilder.Entity("WoW.Database.Models.Realm.Character.PlayerCharacter", b =>
                {
                    b.Property<string>("Name")
                        .HasColumnType("varchar(16)")
                        .HasColumnName("character_name");

                    b.Property<int>("AccountId")
                        .HasColumnType("int")
                        .HasColumnName("account_id");

                    b.Property<int>("CharacterId")
                        .HasColumnType("int")
                        .HasColumnName("character_id");

                    b.Property<int>("Direction")
                        .HasColumnType("int")
                        .HasColumnName("animation_direction");

                    b.Property<int>("HairId")
                        .HasColumnType("int")
                        .HasColumnName("character_hair_id");

                    b.Property<string>("MapId")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("map_id");

                    b.Property<int>("RaceId")
                        .HasColumnType("int")
                        .HasColumnName("character_race_id");

                    b.Property<float>("XPosition")
                        .HasColumnType("float")
                        .HasColumnName("zone_x_position");

                    b.Property<float>("YPosition")
                        .HasColumnType("float")
                        .HasColumnName("zone_y_position");

                    b.HasKey("Name");

                    b.ToTable("characters");
                });

            modelBuilder.Entity("WoW.Database.Models.Realm.Character.PlayerCharacterStatistic", b =>
                {
                    b.Property<int>("CharacterId")
                        .HasColumnType("int")
                        .HasColumnName("character_id");

                    b.Property<int>("Agility")
                        .HasColumnType("int")
                        .HasColumnName("agility_amt");

                    b.Property<int>("Intellect")
                        .HasColumnType("int")
                        .HasColumnName("intellect_amt");

                    b.Property<int>("Spirit")
                        .HasColumnType("int")
                        .HasColumnName("spirit_amt");

                    b.Property<int>("Stamina")
                        .HasColumnType("int")
                        .HasColumnName("stamina_amt");

                    b.Property<int>("Strength")
                        .HasColumnType("int")
                        .HasColumnName("strength_amt");

                    b.HasKey("CharacterId");

                    b.ToTable("character_stats");
                });

            modelBuilder.Entity("WoW.Database.Models.Realm.Chat.ChatCommand", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("command_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("HandlerId")
                        .HasColumnType("longtext")
                        .HasColumnName("handler_id");

                    b.Property<string>("HelpText")
                        .HasColumnType("longtext")
                        .HasColumnName("help_text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("name");

                    b.Property<int>("Security")
                        .HasColumnType("int")
                        .HasColumnName("security_level");

                    b.HasKey("Id");

                    b.ToTable("chat_command");
                });

            modelBuilder.Entity("WoW.Database.Models.Realm.Chat.ChatCommandChild", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("child_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("HandlerId")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("handler_id");

                    b.Property<string>("HelpText")
                        .HasColumnType("longtext")
                        .HasColumnName("help_text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("name");

                    b.Property<int>("ParentId")
                        .HasColumnType("int")
                        .HasColumnName("parent_id");

                    b.Property<int>("Security")
                        .HasColumnType("int")
                        .HasColumnName("security_level");

                    b.HasKey("Id");

                    b.ToTable("chat_command_children");
                });

            modelBuilder.Entity("WoW.Database.Models.Realm.Items.Item", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("description");

                    b.Property<int>("Descriptor")
                        .HasColumnType("int")
                        .HasColumnName("itemtype_id");

                    b.Property<string>("Inventory_ModelId")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("inventory_modelid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("name");

                    b.Property<string>("Rendered_ModelId")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("rendered_modelid");

                    b.HasKey("Id");

                    b.ToTable("Items");
                });

            modelBuilder.Entity("WoW.Database.Models.Realm.NonPlayerCharacter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("Agility")
                        .HasColumnType("int")
                        .HasColumnName("agility_amt");

                    b.Property<int>("FlagType")
                        .HasColumnType("int")
                        .HasColumnName("npc_flag");

                    b.Property<int?>("Intellect")
                        .HasColumnType("int")
                        .HasColumnName("intellect_amt");

                    b.Property<int>("Level")
                        .HasColumnType("int")
                        .HasColumnName("level");

                    b.Property<string>("ModelId")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("model_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("name");

                    b.Property<int?>("Spirit")
                        .HasColumnType("int")
                        .HasColumnName("spirit_amt");

                    b.Property<int?>("Stamina")
                        .HasColumnType("int")
                        .HasColumnName("stamina_amt");

                    b.Property<int?>("Strength")
                        .HasColumnType("int")
                        .HasColumnName("strength_amt");

                    b.HasKey("Id");

                    b.ToTable("npc");
                });

            modelBuilder.Entity("WoW.Database.Models.Realm.NonPlayerCharacterBehavior", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("NpcId")
                        .HasColumnType("int")
                        .HasColumnName("npc_id");

                    b.Property<string>("Script")
                        .HasColumnType("longtext")
                        .HasColumnName("behavior_code_id");

                    b.HasKey("Id");

                    b.ToTable("npc_behavior");
                });
#pragma warning restore 612, 618
        }
    }
}
